"""SDF-, mesh-, and mesh-analysis helpers for dds."""

from ..mesh_analysis import (
    downfacing_mask,
    face_areas,
    face_centroids,
    face_normals,
    mesh_bounds_stats,
    mesh_surface_area,
    mesh_volume_estimate,
    normal_rgb_from_normals,
    overhang_angles,
    support_risk_mask,
    vertex_normals,
)
from .adapters import (
    MeshSDF3,
    density_to_sdf,
    density_to_sdf_field,
    mesh_to_occupancy,
    mesh_to_sdf_field,
    occupancy_to_sdf,
    occupancy_to_sdf_field,
    read_mesh,
    write_mesh,
)
from .mesh import TriangleMesh, density_to_mesh, extract_mesh_from_field, occupancy_to_mesh, sdf_to_mesh
from .ops import difference, dilate, erode, intersection, shell, union
from .sdf import SDF3, GridSDF3, as_sdf3
from .shapes import (
    ORIGIN,
    X,
    Y,
    Z,
    box,
    capped_cone,
    capped_cylinder,
    capsule,
    capsule_chain,
    cone,
    cylinder,
    ellipsoid,
    plane,
    rounded_box,
    rounded_cone,
    rounded_cylinder,
    slab,
    sphere,
    torus,
)
from .transforms import orient, rotate, rotation_matrix, scale, translate

__all__ = [
    "GridSDF3",
    "MeshSDF3",
    "ORIGIN",
    "SDF3",
    "TriangleMesh",
    "X",
    "Y",
    "Z",
    "as_sdf3",
    "box",
    "capped_cone",
    "capped_cylinder",
    "capsule",
    "capsule_chain",
    "cone",
    "cylinder",
    "density_to_mesh",
    "density_to_sdf",
    "density_to_sdf_field",
    "difference",
    "dilate",
    "downfacing_mask",
    "ellipsoid",
    "erode",
    "extract_mesh_from_field",
    "face_areas",
    "face_centroids",
    "face_normals",
    "intersection",
    "mesh_bounds_stats",
    "mesh_to_occupancy",
    "mesh_to_sdf_field",
    "mesh_surface_area",
    "mesh_volume_estimate",
    "normal_rgb_from_normals",
    "occupancy_to_mesh",
    "occupancy_to_sdf",
    "occupancy_to_sdf_field",
    "orient",
    "overhang_angles",
    "plane",
    "read_mesh",
    "rotate",
    "rotation_matrix",
    "rounded_box",
    "rounded_cone",
    "rounded_cylinder",
    "scale",
    "sdf_to_mesh",
    "shell",
    "slab",
    "sphere",
    "support_risk_mask",
    "torus",
    "translate",
    "union",
    "vertex_normals",
    "write_mesh",
]
